# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import database.HandleDatabase  as db
from  UI import login

class Ui_registe_Form(QtWidgets.QWidget):

    def __init__(self):
        super(Ui_registe_Form, self).__init__()
        self.db_handler = db.DatabaseHandler()
        self.setupUi(self)
        self.Form=None
    #     self.setupUi()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.Form=Form
        Form.resize(684, 597)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(200, 60, 251, 71))
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 141, 71))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 270, 101, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 360, 101, 51))
        self.label_4.setObjectName("label_4")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(280, 180, 251, 41))
        self.username.setStyleSheet("height: 30px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"border: 1px solid  rgb(85, 0, 255);")
        self.username.setObjectName("username")
        self.account = QtWidgets.QLineEdit(Form)
        self.account.setGeometry(QtCore.QRect(280, 270, 251, 41))
        self.account.setStyleSheet("height: 30px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"border: 1px solid  rgb(85, 0, 255);")
        self.account.setText("")
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(280, 360, 251, 41))
        self.password.setStyleSheet("height: 30px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"border: 1px solid  rgb(85, 0, 255);")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sure_buttion = QtWidgets.QPushButton(Form)
        self.sure_buttion.setGeometry(QtCore.QRect(380, 440, 111, 51))
        self.sure_buttion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sure_buttion.setStyleSheet("height: 30px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"border: 1px solid  rgb(85, 0, 255);")
        self.sure_buttion.setIconSize(QtCore.QSize(25, 25))
        self.sure_buttion.setObjectName("sure_buttion")
        self.reset_buttion = QtWidgets.QPushButton(Form)
        self.reset_buttion.setGeometry(QtCore.QRect(190, 440, 101, 51))
        self.reset_buttion.setStyleSheet("height: 30px;\n"
"border-radius: 15px;\n"
"padding-left: 10px;\n"
"border: 1px solid  rgb(85, 0, 255);")
        self.reset_buttion.setObjectName("reset_buttion")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        #事件处理部分
        self.reset_buttion.clicked.connect(self.reset)
        self.sure_buttion.clicked.connect(self.registe)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">注册</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">用户名</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">账号</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">密码</span></p></body></html>"))
        self.sure_buttion.setText(_translate("Form", "确定"))
        self.reset_buttion.setText(_translate("Form", "重置"))


    def reset(self):
        self.password.setText("")
        self.account.setText("")
        self.username.setText("")

    def registe(self):
        # 获取用户输入的用户名和密码
        username = self.username.text()
        account = self.account.text()
        password = self.password.text()
        if not username and  not account and not password:
            QtWidgets.QMessageBox.warning(self.Form, '注册失败', '用户名、账号和密码不能为空。')
            self.password.setText("")
            self.account.setText("")
            self.username.setText("")
            return
        try:
            # 调用 DatabaseHandler 中的注册方法
            if self.db_handler.register_user(username=username,account=account, password=password):
                QtWidgets.QMessageBox.information(self.Form, '注册成功', '用户注册成功！')

                login_ui=login.Ui_login_form()

                login_ui.show()
                self.close()

            else:
                QtWidgets.QMessageBox.warning(self.Form ,'注册失败', '用户名已存在，请选择其他用户名。')
        except Exception as e:
            print("error", e)
def create_registe_form():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = Ui_registe_Form()
    registe_ui=QtWidgets.QWidget()
    Form.setupUi(registe_ui)
    registe_ui.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    create_registe_form()
